[package]
name = "bencode_derive"
version = "0.1.0"
authors = ["zskamljic <zan.skamljic@equaleyes.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.9"
quote = "1.0.3"
syn = "1.0.16"

[dev-dependencies]
bencode = { path = "../bencode" }