[package]
name = "torrent"
version = "0.1.0"
authors = ["zskamljic <zan.skamljic@equaleyes.com>"]
edition = "2018"

[dependencies]
bencode = { path = "../bencode" }
bencode_derive = { path = "../bencode_derive" }
sha1 = { path = "../sha1" }