[package]
name = "runner"
version = "0.1.0"
authors = ["zskamljic <zan.skamljic@equaleyes.com>"]
edition = "2018"

[dependencies]
directories = { path = "../directories" }
mock = { path = "../mock" }
torrent = { path = "../torrent" }
watcher = { path = "../watcher" }