[package]
name = "runner"
version = "0.1.0"
authors = ["zskamljic <zan.skamljic@equaleyes.com>"]
edition = "2018"

[dependencies]
bencode = { path = "../bencode" }
directories = { path = "../directories" }
watcher = { path = "../watcher" }